---
# WARN: Double quoted fq search terms required
# fq = 'subject:("Psychology and Psychologists")' # works
# WARN: Add API Key later
params:
  music:
    q: 'Arts'
    fq: 'news_desk:("Arts") AND subject:("Music")'
    sort: 'newest'
    page: 0
    api-key: null
  climate:
    q: 'Climate'
    fq: 'news_desk:("Climate") AND subject:("Global Warming")'
    sort: 'newest'
    page: 0
    api-key: null
  food:
    q: 'Food'
    fq: 'news_desk:("Food")'
    sort: 'newest'
    page: 0
    api-key: null
  psych:
    q: 'Psychology'
    fq: 'news_desk:("Science") AND subject:("Psychology and Psychologists")'
    sort: 'newest'
    page: 0
    api-key: null
  research:
    q: 'Research'
    fq: 'news_desk:("Science") AND subject:("Research")'
    sort: 'newest'
    page: 0
    api-key: null
  star_wars:
    q: 'Star Wars'
    fq: 'creative_works:("Star Wars (Movie)")'
    sort: 'newest'
    page: 0
    api-key: null
  tech:
    q: 'Technology'
    fq: 'news_desk:("Technology")'
    sort: 'newest'
    page: 0
    api-key: null
  travel:
    q: 'Travel'
    fq: 'news_desk:("Travel")'
    sort: 'newest'
    page: 0
    api-key: null
  world:
    q: 'World'
    fq: 'news_desk:("World")'
    sort: 'newest'
    page: 0
    api-key: null
